### ISSUE TITLE
Completion for file-paths/directories

### ISSUE THREAD

**Issue by makkus** [click-contrib/click-completion#6]
Is it possible to do filename completion without having to load all files of a matching folder in the `complete` method? That strikes me as very expensive if there are a lot of files.

Currently, I have something like:

```
    def complete(self, ctx, incomplete):

        if incomplete.startswith("/"):
            path_orig = incomplete
        else:
            path_orig = os.path.join(os.getcwd(), incomplete)

        path, file_prefix = path_orig.rsplit("/", 1)

        result = []
        if not path:
            path = "/"

        for filename in os.listdir(path):

            if not file_prefix or filename.startswith(file_prefix):

                file_path = os.path.join(path, filename)
                if os.path.isdir(file_path):
                    filename += "/"

                if incomplete.startswith("/"):
                    result.append(os.path.join(path, filename))
                else:
                    result.append(filename)

        return result

  
```

This will complete a folder with an appended '/', but also a whitespace, and there's no way to complete on the content of this folder? Am I missing something? Thanks!

**Comment by glehmann** [comment]
I don't think there is currently a great way to do that. That definitely something that would be nice, if someone wants to give it a try!

For now, in our private application, we are completing with both the directory name and the directory name with a trailing slash:

```
$ myapp f<tab>
dir1
dir1/
dir2
dir2/
```

because there are two entries that begin exactly the same, the completion is done up to the full dir name, without the slash, and without space, so it is possilbe to continue the completion process.
Obviously the drawback is that the completion list is polluted by twice the amount of entries…

**Comment by makkus** [comment]
Ah, nice workaround, thanks! Will use that for now.

**Comment by flokno** [comment]
Hi @makkus and @glehmann , could you give a more complete example on how `def complete ..` is used to perform filename completion?

I use the fish shell and the autocompletion is currently useless to me since filenames are not completed :/
